### ISSUE TITLE
Holi

### ISSUE THREAD

**Issue by gonzalezge** [julianchitiva/julianchitiva.github.io#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the feature request template to provide clearer instructions and examples for each section, making it easier for users to submit well-structured feature requests.

You can review changes in this commit: https://github.com/jjyutm4532/julianchitiva-julianchitiva.github.io-1/commit/398d4fec2f15162055508a09ad6bf56485d077d8.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
